################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_LIBXML-2.0 "libxml-2.0")
    if (PC_LIBXML-2.0_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_LIBXML-2.0_CFLAGS} ${PC_LIBXML-2.0_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_LIBXML-2.0_INCLUDE_HINTS ${PC_LIBXML-2.0_INCLUDE_DIRS} ${PC_LIBXML-2.0_INCLUDE_DIRS}/*)
        set(PC_LIBXML-2.0_LIBRARY_HINTS ${PC_LIBXML-2.0_LIBRARY_DIRS} ${PC_LIBXML-2.0_LIBRARY_DIRS}/*)
    endif(PC_LIBXML-2.0_FOUND)
endif (NOT MSVC)

find_path (
    LIBXML-2.0_INCLUDE_DIRS
    NAMES libxml/xmlversion.h
    HINTS ${PC_LIBXML-2.0_INCLUDE_HINTS}
)

find_library (
    LIBXML-2.0_LIBRARIES
    NAMES libxml-2.0
    HINTS ${PC_LIBXML-2.0_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    LIBXML-2.0
    REQUIRED_VARS LIBXML-2.0_LIBRARIES LIBXML-2.0_INCLUDE_DIRS
)
mark_as_advanced(
    LIBXML-2.0_FOUND
    LIBXML-2.0_LIBRARIES LIBXML-2.0_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
